apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-organization-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-organization-template
  template:
    metadata:
      labels:
        app: ms-organization-template
    spec:
      containers:
        - name: ms-organization-template
          image: ms-organization-template:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: SPRING_CONFIG_IMPORT
              value: ${SPRING_CONFIG_IMPORT:optional:configserver:disabled}
          readinessProbe:
            httpGet:
              path: /custom-path/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /custom-path/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
