apiVersion: v1
kind: Service
metadata:
  name: ms-organization-template-service
spec:
  selector:
    app: ms-organization-template
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
